### ISSUE TITLE
pin tifffile dependency to something greater than version 2023.*

### ISSUE THREAD

**Issue by kaczmarj** [SBU-BMI/wsinfer#154]
Using a tifffile version from 2021 was incompatible with tiffslide. To be on the safe side, let's pin the tifffile version to something equal to or newer than 2023.*.

The change would have to be made in `setup.cfg`.

**Comment by kaczmarj** [comment]
@swaradgat19 - make a fork of the project, branch off of main, commit the change, and submit a pr back to this repo

**Comment by kaczmarj** [comment]
@swaradgat19 - we should pin the following dependencies

```
imagecodecs >= 2023.7.10  # https://github.com/Bayer-Group/tiffslide/issues/72#issuecomment-1630091390
tifffile >= 2023.1.23
tiffslide >= 2.2.0  # https://github.com/Bayer-Group/tiffslide/issues/72#issuecomment-1631015274
```

**Comment by swaradgat19** [comment]
Got it. Making the changes

**Comment by swaradgat19** [comment]
@kaczmarj - imagecodec >= 2023.7.10 will go in the dev section right? And tifffile and tiffslide in the requires section

**Comment by kaczmarj** [comment]
good question. let's move it into the `install_requires` section. 

`imagecodecs` is a dependency of `tifffile` and `tiffslide`, and that imagecodec had a speed improvement in 2023.7.10 that is relevant to our use cases.

**Comment by swaradgat19** [comment]
Ah makes sense. I have opened a PR
