### ISSUE TITLE
Incorrect command to convert model outputs to GeoJson in documentation

### ISSUE THREAD

**Issue by swaradgat19** [SBU-BMI/wsinfer#175]
The command to convert the model outputs to geojson format probably has a typo. On the documentation, it is given: `wsirun togeojson results/ geojson-results/`. This command gives the error: `Command not found`

On changing it to: `wsinfer run togeojson Results/ geojson-Results/`, it gives the following error: 

```pythonUsage: wsinfer run [OPTIONS]
Try 'wsinfer run --help' for help.

Error: Missing option '-i' / '--wsi-dir'. 
```

What is the correct command to convert the model-outputs to the geojson format?

[Link](https://wsinfer.readthedocs.io/en/latest/user_guide.html#convert-model-outputs-to-geojson-qupath) to the command in documentation

**Comment by swaradgat19** [comment]
Sure. I'll do it

**Comment by swaradgat19** [comment]
For the Stony Brook format, is this the correct command?

```rst
  wsinfer tosbu \
      --wsi-dir slides/ \
      --execution-id UNIQUE_ID_HERE \
      --study-id STUDY_ID_HERE \
      --make-color-text \
      --num-processes 16 \
      results/ \
      results/model-outputs-sbubmi/
```

**Comment by kaczmarj** [comment]
>For the Stony Brook format, is this the correct command?

it is, but the stony brook conversion isn't quite finished yet... i wouldn't use it at this point.
