### ISSUE TITLE
consider making releases automatically with intuit's 'auto'

### ISSUE THREAD

**Issue by kaczmarj** [SBU-BMI/wsinfer#183]
the `auto` package can help us make releases when merging to main. it seems prudent to release often, because updates will be available sooner via pip and conda.

the docs are here https://intuit.github.io/auto/docs/configuration/non-npm 

see this github workflow yaml file for an example https://github.com/ReproNim/neurodocker/blob/6be21d9fff7163fd5adc5911b8bc8ef9cd7f92aa/.github/workflows/release.yml

@swaradgat19 - i will take care of this issue but you're welcome to help out, especially if you want to learn more about packaging python projects so they can be downloaded via pip like `pip install wsinfer`.

**Comment by kaczmarj** [comment]
fixed by https://github.com/SBU-BMI/wsinfer/commit/b05b7ee29e8482d2866c8e076a6f417fc7eda02a

instead of using intuit's auto, it was more intuitive to use pypa's github actions.

**Comment by swaradgat19** [comment]
So we're going to use GitHub actions itself? Should I look into the tool?

**Comment by kaczmarj** [comment]
yes we will use github actions. either way, we would have used github actions. but i was wondering whether to use `auto` or some more standard python build tools. i am more familiar with the standard python build tools (like the `build` command line tool)

i added a github action workflow to build wsinfer into a python wheel and publish that to PyPI whenever a release is made. https://github.com/SBU-BMI/wsinfer/blob/b05b7ee29e8482d2866c8e076a6f417fc7eda02a/.github/workflows/publish-to-pypi.yml
