### ISSUE TITLE
[ENH] add strided tiles

### ISSUE THREAD

**Issue by kaczmarj** [SBU-BMI/wsinfer#202]
add inference on overlapping patches. this can smooth outputs and could be more informative.

we will need to resolve how to save these outputs. at the moment, each row of the output CSVs holds one patch. we could simply include all of the patches, despite overlapping. or we could do some post-processing of the outputs, where we merge patch outputs and recover non-overlapping patches. i'm not sure yet.

i would appreciate any thoughts on how the outputs should be structured

cc: @xalexalex 

related to https://github.com/qupath/qupath-extension-wsinfer/issues/46

**Comment by xalexalex** [comment]
I think the most transparent way would be to simply leave all (overlapping) tiles in the csv and let the user (or consumer, e.g. the qupath extension) decide how to handle them. Doing things like averaging could work for simple binary models, but it might not do what the user expects in multiclass classification tasks and in edge cases (such as edge tiles :) ).

However I might be mistaken and averaging might be the most convenient choice. I'm interested in other opinions and will be following this thread. Thanks for the ping!

p.s. doing inference on strided tiles might open up room for performance improvements (model architecture-dependent). But it's best if we discuss these later.

**Comment by kaczmarj** [comment]
the step size in these lines would have to be updated to support strided patches. i think we could add an argument to this function like `overlap` where we specify the ratio of overlaps. default would be zero, meaning no overlap. 0.2 would be 20% overlap, and 0.5 would be 50% overlap.

in the case of 0 overlap (default), the step size would be `patch_size_pixels`. with 0.2 overlap, the step size would be `(1-0.2)*patch_size_pixels == `0.8*patch_size_pixels`.

the `overlap` variable would have to bubble up the call stack, up to the command line interface.

https://github.com/SBU-BMI/wsinfer/blob/0b1208c78ff1c8ba5e83332a7401d9ab7e6e3062/wsinfer/patchlib/patch.py#L157-L164
