### ISSUE TITLE
CTransPath

### ISSUE THREAD

**Issue by masudalynn0704** [SBU-BMI/wsinfer#223]
Hi Jakub,
Greetings from Zheng. WSInfer is a extremely useful tool for my study. I saw you share the torchscript of CTransPath in your model. May I know if the CTransPath model could be loaded on WSInfer QuPath extension? At the same time, our studies are focusing on human peripheral blood cells. I'd like to know if there have any model that could be utilized in WSInfer QuPath extension to recognize such as neutrophils, eosinophils, plasma cells,etc? Many thanks for you and I looking forward to hearing any advice from you.

**Comment by kaczmarj** [comment]
hi @masudalynn0704 - thanks for reaching out. i responded to your query in https://huggingface.co/kaczmarj/CTransPath/discussions/1

i will close this now
